#!/usr/bin/env bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════════════════════
#  AutoGen Enterprise — Installer
#  Detects available ports, generates .env, builds & starts all containers.
# ══════════════════════════════════════════════════════════════════════════════

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

banner() {
  echo ""
  echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}${BOLD}║   🤖 AutoGen Enterprise — Installer         ║${NC}"
  echo -e "${CYAN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
  echo ""
}

info()    { echo -e "${GREEN}[✓]${NC} $1"; }
warn()    { echo -e "${YELLOW}[!]${NC} $1"; }
error()   { echo -e "${RED}[✗]${NC} $1"; }
step()    { echo -e "${CYAN}[→]${NC} $1"; }

# ── Check prerequisites ──────────────────────────────────────────────────────
check_prerequisites() {
  step "Checking prerequisites..."

  if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Please install Docker first:"
    echo "  https://docs.docker.com/get-docker/"
    exit 1
  fi
  info "Docker found: $(docker --version | head -1)"

  if ! command -v docker compose &> /dev/null && ! command -v docker-compose &> /dev/null; then
    error "Docker Compose is not installed."
    exit 1
  fi

  if command -v docker compose &> /dev/null; then
    COMPOSE_CMD="docker compose"
  else
    COMPOSE_CMD="docker-compose"
  fi
  info "Docker Compose found"

  if ! docker info &> /dev/null; then
    error "Docker daemon is not running. Please start Docker first."
    exit 1
  fi
  info "Docker daemon is running"
  echo ""
}

# ── Port detection ────────────────────────────────────────────────────────────
is_port_available() {
  local port=$1
  if command -v ss &> /dev/null; then
    ! ss -tlnp 2>/dev/null | grep -q ":${port} " 2>/dev/null
  elif command -v netstat &> /dev/null; then
    ! netstat -tlnp 2>/dev/null | grep -q ":${port} " 2>/dev/null
  elif command -v lsof &> /dev/null; then
    ! lsof -iTCP:${port} -sTCP:LISTEN &>/dev/null
  else
    # Fallback: try to open a connection (if it fails, port is likely free)
    ! (echo > /dev/tcp/127.0.0.1/${port}) 2>/dev/null
  fi
}

find_available_port() {
  local preferred=$1
  local label=$2
  local port=$preferred

  while ! is_port_available $port; do
    warn "Port $port is in use, trying $(($port + 1))..."
    port=$(($port + 1))
    if [ $port -gt $(($preferred + 100)) ]; then
      error "Could not find an available port near $preferred for $label"
      exit 1
    fi
  done
  echo $port
}

detect_ports() {
  step "Detecting available ports..."

  FRONTEND_PORT=$(find_available_port 3000 "Frontend")
  BACKEND_PORT=$(find_available_port 8000 "Backend API")
  DB_PORT=$(find_available_port 5432 "PostgreSQL")
  ADMINER_PORT=$(find_available_port 8080 "Adminer")

  info "Frontend  → port ${FRONTEND_PORT}"
  info "Backend   → port ${BACKEND_PORT}"
  info "Postgres  → port ${DB_PORT}"
  info "Adminer   → port ${ADMINER_PORT}"
  echo ""
}

# ── Generate configuration ───────────────────────────────────────────────────
generate_env() {
  step "Generating .env file..."

  cat > .env <<EOF
# ── AutoGen Enterprise — Auto-generated by install.sh ──
# Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Ports
FRONTEND_PORT=${FRONTEND_PORT}
BACKEND_PORT=${BACKEND_PORT}
DB_PORT=${DB_PORT}
ADMINER_PORT=${ADMINER_PORT}

# Database
DATABASE_URL=postgresql://autogen:autogen123@db:5432/autogen_db
POSTGRES_USER=autogen
POSTGRES_PASSWORD=autogen123
POSTGRES_DB=autogen_db

# Redis
REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

# Worker
MAX_ROUNDS=12
WORKSPACES_DIR=/tmp/workspaces

# Frontend
REACT_APP_API_URL=http://localhost:${BACKEND_PORT}
EOF

  info ".env file created"
}

generate_compose_override() {
  step "Generating docker-compose.override.yml with detected ports..."

  cat > docker-compose.override.yml <<EOF
# Auto-generated by install.sh — port overrides
version: '3.8'

services:
  backend:
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}

  frontend:
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}

  db:
    ports:
      - "${DB_PORT}:5432"

  adminer:
    ports:
      - "${ADMINER_PORT}:8080"
EOF

  info "docker-compose.override.yml created"
  echo ""
}

# ── Build and start ──────────────────────────────────────────────────────────
build_and_start() {
  step "Building and starting containers (this may take a few minutes)..."
  echo ""

  $COMPOSE_CMD down --remove-orphans 2>/dev/null || true
  $COMPOSE_CMD up -d --build

  echo ""
  info "All containers started!"
  echo ""
}

# ── Health check ──────────────────────────────────────────────────────────────
wait_for_health() {
  step "Waiting for services to become healthy..."

  local max_wait=90
  local elapsed=0

  while [ $elapsed -lt $max_wait ]; do
    if curl -sf "http://localhost:${BACKEND_PORT}/health" > /dev/null 2>&1; then
      info "Backend is healthy!"
      break
    fi
    sleep 3
    elapsed=$((elapsed + 3))
    echo -ne "  Waiting... ${elapsed}s / ${max_wait}s\r"
  done

  if [ $elapsed -ge $max_wait ]; then
    warn "Backend didn't become healthy within ${max_wait}s."
    warn "Check logs with: $COMPOSE_CMD logs backend"
  fi
  echo ""
}

# ── Print summary ────────────────────────────────────────────────────────────
print_summary() {
  echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}${BOLD}║   ✅ Installation Complete!                  ║${NC}"
  echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
  echo ""
  echo -e "  ${BOLD}🌐 App:${NC}      http://localhost:${FRONTEND_PORT}"
  echo -e "  ${BOLD}🔌 API:${NC}      http://localhost:${BACKEND_PORT}"
  echo -e "  ${BOLD}🗄️  Adminer:${NC}  http://localhost:${ADMINER_PORT}"
  echo -e "  ${BOLD}🐘 Postgres:${NC} localhost:${DB_PORT}"
  echo ""
  echo -e "  ${BOLD}Quick start:${NC}"
  echo "  1. Open http://localhost:${FRONTEND_PORT}"
  echo "  2. Click ⚙️ Settings → enter your API key"
  echo "  3. Describe a task and click 🚀 Start Task"
  echo ""
  echo -e "  ${BOLD}Useful commands:${NC}"
  echo "  View logs:     $COMPOSE_CMD logs -f"
  echo "  Stop:          $COMPOSE_CMD down"
  echo "  Restart:       $COMPOSE_CMD restart"
  echo "  Uninstall:     bash uninstall.sh"
  echo ""
}

# ── Main ─────────────────────────────────────────────────────────────────────
banner
check_prerequisites
detect_ports
generate_env
generate_compose_override
build_and_start
wait_for_health
print_summary
