#!/usr/bin/env bash
set -euo pipefail

# ══════════════════════════════════════════════════════════════════════════════
#  AutoGen Team Builder — Installer
#  Detects an available port, builds & starts the Streamlit container.
# ══════════════════════════════════════════════════════════════════════════════

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}${BOLD}║   🤖 AutoGen Team Builder — Installer       ║${NC}"
  echo -e "${CYAN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
  echo ""
}

info()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; }
step()  { echo -e "${CYAN}[→]${NC} $1"; }

# ── Check prerequisites ──────────────────────────────────────────────────────
check_prerequisites() {
  step "Checking prerequisites..."

  if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Please install Docker first:"
    echo "  https://docs.docker.com/get-docker/"
    exit 1
  fi
  info "Docker found: $(docker --version | head -1)"

  if command -v docker compose &> /dev/null; then
    COMPOSE_CMD="docker compose"
  elif command -v docker-compose &> /dev/null; then
    COMPOSE_CMD="docker-compose"
  else
    error "Docker Compose is not installed."
    exit 1
  fi
  info "Docker Compose found"

  if ! docker info &> /dev/null; then
    error "Docker daemon is not running. Please start Docker first."
    exit 1
  fi
  info "Docker daemon is running"
  echo ""
}

# ── Port detection ────────────────────────────────────────────────────────────
is_port_available() {
  local port=$1
  if command -v ss &> /dev/null; then
    ! ss -tlnp 2>/dev/null | grep -q ":${port} " 2>/dev/null
  elif command -v netstat &> /dev/null; then
    ! netstat -tlnp 2>/dev/null | grep -q ":${port} " 2>/dev/null
  elif command -v lsof &> /dev/null; then
    ! lsof -iTCP:${port} -sTCP:LISTEN &>/dev/null
  else
    ! (echo > /dev/tcp/127.0.0.1/${port}) 2>/dev/null
  fi
}

find_available_port() {
  local preferred=$1
  local port=$preferred

  while ! is_port_available $port; do
    warn "Port $port is in use, trying $(($port + 1))..."
    port=$(($port + 1))
    if [ $port -gt $(($preferred + 50)) ]; then
      error "Could not find an available port near $preferred"
      exit 1
    fi
  done
  echo $port
}

detect_port() {
  step "Detecting available port..."
  APP_PORT=$(find_available_port 8501)
  info "App will run on port ${APP_PORT}"
  echo ""
}

# ── Generate .env ─────────────────────────────────────────────────────────────
generate_env() {
  step "Generating .env..."
  cat > .env <<EOF
# AutoGen Team Builder — Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
APP_PORT=${APP_PORT}
EOF
  info ".env created"
}

# ── Build and start ──────────────────────────────────────────────────────────
build_and_start() {
  step "Building and starting container (first build may take 2-5 minutes)..."
  echo ""

  $COMPOSE_CMD down --remove-orphans 2>/dev/null || true
  $COMPOSE_CMD up -d --build

  echo ""
  info "Container started!"
  echo ""
}

# ── Wait for health ──────────────────────────────────────────────────────────
wait_for_health() {
  step "Waiting for Streamlit to start..."

  local max_wait=120
  local elapsed=0

  while [ $elapsed -lt $max_wait ]; do
    if curl -sf "http://localhost:${APP_PORT}/_stcore/health" > /dev/null 2>&1; then
      info "Streamlit is healthy!"
      break
    fi
    sleep 3
    elapsed=$((elapsed + 3))
    echo -ne "  Waiting... ${elapsed}s / ${max_wait}s\r"
  done

  if [ $elapsed -ge $max_wait ]; then
    warn "Streamlit didn't respond within ${max_wait}s."
    warn "Check logs: $COMPOSE_CMD logs app"
  fi
  echo ""
}

# ── Summary ──────────────────────────────────────────────────────────────────
print_summary() {
  echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}${BOLD}║   ✅ Installation Complete!                  ║${NC}"
  echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
  echo ""
  echo -e "  ${BOLD}🌐 Open:${NC}  http://localhost:${APP_PORT}"
  echo ""
  echo -e "  ${BOLD}Quick start:${NC}"
  echo "  1. Open the URL above"
  echo "  2. Enter your API key in the sidebar"
  echo "  3. Describe a task and click 🚀 Build Team & Execute"
  echo ""
  echo -e "  ${BOLD}Commands:${NC}"
  echo "  Logs:       $COMPOSE_CMD logs -f app"
  echo "  Stop:       $COMPOSE_CMD down"
  echo "  Restart:    $COMPOSE_CMD restart"
  echo "  Uninstall:  bash uninstall.sh"
  echo ""
}

# ── Main ─────────────────────────────────────────────────────────────────────
banner
check_prerequisites
detect_port
generate_env
build_and_start
wait_for_health
print_summary
